### ISSUE TITLE
Boogie has changed their dependency filenames...

### ISSUE THREAD

**Issue by zestysoft** [tech-srl/esh#1]
In the instructions to build esh is a section on copying files from the Boogie compile over to esh's references folder.  However, the files generated from a build in Boogie are no longer named the way esh is expecting them.

For instance:
AbsInt.dll is now named BoogieAbsInt.dll

**Comment by nimrodpar** [comment]
Indeed, we will soon specify the exact version of boogie and z3 used.

If you already patched this, we would appreciate a pull request, thanks.

**Comment by Yanivmd** [comment]
last commit should take care of this.
