### ISSUE TITLE
error CS0006

### ISSUE THREAD

**Issue by yueyuep** [tech-srl/esh#2]
I download the boogie and build in visual studio2015 according the guidances,there is a error 
error CS0006: Metadata file 'K:\boogie-master\Source\Concurrency\bin\Release\BoogieConcurrency.dll' could not be found.ry many methods but could't figure out.

**Comment by Yanivmd** [comment]
Hi,

Please use commit 'c8c15f672dc42fca1db9b0f20549ef49b48889e8' from the Boogie git repo.

**Comment by yueyuep** [comment]
hi,thanks your answer,
is it incorrect version of boogie ? it means that i need git checked the boogie according the SHA key:'c8c15f672dc42fca1db9b0f20549ef49b48889e8'  i am not good at git command.

**Comment by nimrodpar** [comment]
Yes, Esh works with the Boogie version that was committed at 'c8c15f672dc42fca1db9b0f20549ef49b48889e8', so you'll need to git checkout that specific key.

**Comment by yueyuep** [comment]
thank you very much.
